MARKER_VALID = "\u2713"
MARKER_NOISE_START = "\u274Cs__"
MARKER_NOISE_END = "\u274Ce__"
MARKER_INTENDED_CORRUPTION = "\u25BC"

SPECIAL_SYMBOLS = {
    MARKER_VALID: 1,
    MARKER_NOISE_START: 2,
    MARKER_NOISE_END: 3,
}
